name: craft-boilerplate
type: craftcms
docroot: web
php_version: '8.3'
webserver_type: apache-fpm
database:
    type: mariadb
    version: '10.6'
use_dns_when_possible: true
composer_version: '2'
nodejs_version: 'auto'
web_environment:
    - VITE_SERVER_URL=${DDEV_PRIMARY_URL_WITHOUT_PORT}
    - VITE_SERVER_PORT=5173
    - VITE_SERVER_PRIVATE_PORT=3000
web_extra_exposed_ports:
    - name: vite
      container_port: 3000
      http_port: 3000
      https_port: 5173
